import type { DigestData } from '../types.js'
import { formatCompactNumber, oneLineCommit, toDateString } from '../utils/format.js'

/** 单仓库区块的 Markdown */
function renderRepoSection(repo: DigestData['repos'][number]): string {
  const lines: string[] = []
  lines.push(`### ⭐ ${repo.owner}/${repo.name}`)
  lines.push(
    `**${formatCompactNumber(repo.stars)} stars** · [GitHub](${repo.url})`,
  )
  if (repo.description) lines.push(`> ${repo.description}`)

  if (repo.latestRelease) {
    lines.push(
      `- 🚀 **Latest release:** \`${repo.latestRelease.tagName}\` (${repo.latestRelease.publishedAt})${repo.latestRelease.name ? ` — ${oneLineCommit(repo.latestRelease.name, 60)}` : ''}`,
    )
  }

  if (repo.recentCommits.length > 0) {
    lines.push('', 'Recent commits:')
    for (const commit of repo.recentCommits.slice(0, 5)) {
      lines.push(`- \`${commit.date}\` ${commit.author}: ${commit.message}`)
    }
  }

  return lines.join('\n')
}

/** HN 关键词区块的 Markdown */
function renderHNSection(
  keywords: string[],
  stories: DigestData['hnStories'],
): string {
  const lines: string[] = []
  let anyStories = false

  for (const keyword of keywords) {
    const list = stories[keyword] ?? []
    if (list.length === 0) continue
    anyStories = true

    lines.push(`### 🗞️ ${keyword}`)
    for (const story of list.slice(0, 5)) {
      const link = story.url
        ? `[${story.title}](${story.url})`
        : story.title
      lines.push(
        `- ${link} · ${story.score} points · by ${story.by} · [HN](https://news.ycombinator.com/item?id=${story.id})`,
      )
    }
    lines.push('')
  }

  if (!anyStories) {
    lines.push('*没有命中关键词的热门故事。*')
  }

  return lines.join('\n')
}

/** 渲染完整摘要 Markdown */
export function renderDigest(data: DigestData, keywords: string[]): string {
  const lines: string[] = []
  lines.push(`# Weekly Developer Digest`)
  lines.push('')
  lines.push(`> Generated at ${data.generatedAt} · by weekly-digest-cli`)
  lines.push('')

  lines.push('## 📦 GitHub Repos')
  lines.push('')
  for (const repo of data.repos) {
    lines.push(renderRepoSection(repo))
    lines.push('')
  }

  lines.push('## 🔥 Hacker News')
  lines.push('')
  lines.push(renderHNSection(keywords, data.hnStories))

  lines.push('')
  lines.push('---')
  lines.push('*Generated by [weekly-digest-cli](https://github.com/luckerbai/weekly-digest-cli)*')

  return lines.join('\n')
}

/** 构建 DigestData 后调用 renderDigest 的便捷函数 */
export function buildDigestMarkdown(
  repos: DigestData['repos'],
  hnStories: DigestData['hnStories'],
  keywords: string[],
  generatedAt = new Date().toISOString(),
): string {
  return renderDigest({ generatedAt, repos, hnStories }, keywords)
}

export { toDateString }
